A failing acctest
Regressed some time ago. Fails with

(source environment && source ${ACTIVATE} && cd test/acceptance && nose2)

	Command: /home/OXFORDNANOLABS/strygubenko/src/sloika/bin/create_hdf5.py

	Command error output:
		Traceback (most recent call last):
		  File "/home/OXFORDNANOLABS/strygubenko/src/sloika/bin/create_hdf5.py", line 8, in <module>
		    from sloika import batch, sloika_dtype
		ImportError: cannot import name sloika_dtype

	Command exit code: 1
F
======================================================================
FAIL: test_usage (test_create_hdf5.CreateHDF5Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/OXFORDNANOLABS/strygubenko/src/sloika/test/acceptance/test_create_hdf5.py", line 23, in test_usage
    self.assertEqual(return_code, 2)
AssertionError: 1 != 2