Stick with py3 as suffix convention + added missing env var
Switching to python3 as a main tox env highlighted a problem:

  File "/home/semen/src/sloika/build/tmpenvPy3/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 174, in finalize_options
    self.egg_version = self.tagged_version()
  File "/home/semen/src/sloika/build/tmpenvPy3/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 264, in tagged_version
    return safe_version(version + self.vtags)
TypeError: can't concat bytes to str

ERROR: FAIL could not package project - v = InvocationError('/home/semen/src/sloika/build/tmpenvPy3/bin/python3 /home/semen/src/sloika/setup.py sdist --formats=zip --dist-dir /home/semen/src/sloika/.tox/dist (see /home/semen/src/sloika/.tox/log/tox-0.log)', 1)